# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Uym1I53w5SgJgLZhYa6Oaw_yRAnWL144
"""

import argparse
import time
from pymodbus.client import ModbusSerialClient

def parse_baudrates(s: str) -> list[int]:
    """Parse comma-separated baudrates."""
    return [int(x.strip()) for x in s.split(",") if x.strip()]


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Modbus RTU Auto-Scanner: Brute-force unknown slave ID and baudrate",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument(
        "--port",
        required=True,
        help="Serial port (e.g. COM3 on Windows, /dev/ttyUSB0 on Linux)",
    )
    parser.add_argument(
        "--baudrates",
        default="9600, 19200",
        help="Comma-separated list of baudrates to test (most common first)",
    )
    parser.add_argument(
        "--min-slave",
        type=int,
        default=1,
        help="Minimum slave ID to test",
    )
    parser.add_argument(
        "--max-slave",
        type=int,
        default=10,
        help="Maximum slave ID to test (1-247 possible, but higher values make scan very slow)",
    )
    parser.add_argument(
        "--timeout",
        type=float,
        default=0.5,
        help="Timeout in seconds per request (lower = faster scan, but risk of missing slow devices)",
    )
    parser.add_argument(
        "--test-address",
        type=int,
        default=793,
        help="Holding register address to test read (0 is common; even if invalid, a response confirms communication)",
    )
    parser.add_argument(
        "--test-count",
        type=int,
        default=1,
        help="Number of registers to read",
    )
    parser.add_argument(
        "--stop-on-first",
        action="store_true",
        help="Stop after finding the first working combination",
    )

    args = parser.parse_args()

    baudrates = parse_baudrates(args.baudrates)
    print(f"Starting Modbus RTU scanner on port {args.port}")
    print(f"Testing baudrates: {baudrates}")
    print(f"Slave IDs: {args.min_slave} to {args.max_slave}")
    print(f"Test: read holding register {args.test_address} (count={args.test_count})")
    print(f"Timeout per request: {args.timeout}s\n")
    print("Note: This uses standard 8N1 (8 data bits, no parity, 1 stop bit).")
    print("      If your device uses even/odd parity, edit the code to add parity loops.\n")

    found = []

    for baud in baudrates:
        print(f"→ Testing baudrate {baud}...")
        for slave in range(args.min_slave, args.max_slave + 1):
            print(f"  → Trying slave ID {slave}...", end=" ")

            client = ModbusSerialClient(
                port=args.port,
                baudrate=baud,
                bytesize=8,
                parity="N",      # Most common for Modbus RTU
                stopbits=1,
                timeout=args.timeout,
                retries=0
                # framer defaults to RTU in current pymodbus
            )

            if not client.connect():
                print("Failed to open serial port")
                client.close()
                continue

            try:
                # Attempt to read - any response (success or exception response) means communication works
                response = client.read_holding_registers(
                    address=args.test_address,
                    count=args.test_count,
                    device_id=slave,
                )

                # If we reach here, the device responded (correct baud + slave ID)
                print("SUCCESS!")
                if not response.isError():
                    print(f"    → Valid response: {response.registers}")
                else:
                    print(f"    → Device responded with Modbus exception (still confirms connection)")

                found.append((baud, slave, response))
                if args.stop_on_first:
                    client.close()
                    break

            except Exception as e:
                # Timeout, CRC error, no response, wrong baud, wrong slave, etc.
                print(f"no response ({type(e).__name__})")
            finally:
                client.close()

            # Tiny delay between attempts to avoid flooding the bus
            time.sleep(1)

        if found and args.stop_on_first:
            break

    print("\n" + "=" * 60)
    if found:
        print("✅ FOUND WORKING PARAMETER(S):")
        for baud, slave, resp in found:
            print(f"   • Baudrate = {baud}, Slave ID = {slave}")
            if not resp.isError():
                print(f"       Sample data: {resp.registers}")
        print("\nYou can now use these parameters in your final Modbus client.")
    else:
        print("❌ No device found with the tested parameters.")
        print("   Tips:")
        print("   • Try expanding --min-slave / --max-slave")
        print("   • Add other common baudrates (e.g. 57600, 115200)")
        print("   • Check physical connection, RS-485 wiring, termination resistor")
        print("   • Try different parity (edit code: parity='E' or 'O')")
        print("   • Increase --timeout if device is very slow")

    print("=" * 60)


if __name__ == "__main__":
    main()